apiVersion: v1
kind: Pod
metadata:
  name: title
  namespace: default
  labels:
    role: title
spec:
  containers:
    - name: title
      image: registry.cn-hangzhou.aliyuncs.com/ls-2018/mygo:v1.24.1
      command:
        - "/bin/bash"
        - "-c"
        - "sleep 1d"
