apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: stock-service-example
  namespace: default
  labels:
    a: "1"
  annotations:
    b: "1"
spec:
  template:
    metadata:
      name: stock-service-example-v1
      labels:
        c: "1"
      annotations:
#        "autoscaling.knative.dev/min-scale": "0"
#        "autoscaling.knative.dev/max-scale": "10"
        "autoscaling.knative.dev/target": "10" # 设置当前最大并发请求数为10。
#        "autoscaling.knative.dev/window":  "20s"
        "autoscaling.knative.dev/metric": "rps"
#        "autoscaling.knative.dev/panic-window-percentage": "10"
#        "autoscaling.knative.dev/target-utilization-percentage": "10"
    spec:
#      containerConcurrency: 10
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/ls-2018/knative:helloworld-go
          env:
            - name: RESOURCE
              value: v1
          readinessProbe:
            httpGet:
              path: /
            initialDelaySeconds: 0
            periodSeconds: 3