apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: stock-service-example
  namespace: default
spec:
  template:
    metadata:
      name: stock-service-example-v3
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/knative-sample/rest-api-go:v1
          env:
            - name: RESOURCE
              value: v3
          readinessProbe:
            httpGet:
              path: /
            initialDelaySeconds: 0
            periodSeconds: 3
  traffic:
    - tag: v1
      revisionName: stock-service-example-v1
      percent: 50
    - tag: v2
      revisionName: stock-service-example-v2
      percent: 50
    - tag: latest
      latestRevision: true
      percent: 0