apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    metadata:
      annotations:
#        'autoscaling.knative.dev/min-scale': "2"
#        'autoscaling.knative.dev/max-scale': "5"
#    'serving.knative.dev/progress-deadline'
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/ls-2018/knative:helloworld-go2
        env:
        - name: TARGET
          value: "Go Sample v1"



